name: ci
on: push
jobs:
  test:
    name: CI validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
      