name: ci
on: push
jobs:
  test:
    name: CI validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.9'
      - name: Install dependencies
        run: |
          go mod download
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      